---
# This is a basic workflow to help you get started with Actions

name: centos6-rpm

on:
  push:
    tags:
      - 'el6*'

jobs:
  build-el6-rpm:
    # The type of runner that the container will run on
    runs-on: ubuntu-latest

    # The image of docker that the job will run on
    container:
      image: "centos:6"
      options: --dns 8.8.8.8

    steps:
      - uses: actions/checkout@v1
      - name: Build RPM Package
        run: |
          for repo_file in /etc/yum.repos.d/*.repo; do \
              sed -i 's/^mirrorlist=/#mirrorlist=/g' $repo_file \
              && sed -i 's/^#\s*baseurl=/baseurl=/g' $repo_file \
              && sed -i 's/mirror.centos.org/vault.centos.org/g' $repo_file \
              && sed -i 's/http:\/\/vault.centos.org/https:\/\/vault.centos.org/g' $repo_file \
              ; \
          done

          yum install -y spectool git doxygen gcc createrepo openssl-devel \
            yum-utils
          mkdir -p ~/rpmbuild/{SOURCES,BUILD,BUILDROOT,RPMS,SRPMS,SPECS}

          cp SOURCES/* ~/rpmbuild/SOURCES/

          printf "[local-base]\n\
          name=Local Base Repo\n\
          baseurl=file://$HOME/rpmbuild/RPMS/x86_64/\n\
          skip_if_unavailable=True\n\
          gpgcheck=0\n\
          repo_gpgcheck=0\n\
          enabled=1\n\
          enabled_metadata=1" | tee /etc/yum.repos.d/local-base.repo

          curl -SsLo /etc/yum.repos.d/openresty.repo \
            https://openresty.org/package/centos/openresty.repo
          yum install -y openresty-openssl111-devel

          spectool -gf -C ~/rpmbuild/SOURCES SPECS/ccache.spec
          yum-builddep -y SPECS/ccache.spec
          cp SPECS/ccache.spec ~/rpmbuild/SPECS/ \
            && rpmbuild -ba ~/rpmbuild/SPECS/ccache.spec
      - name: Check RPM Packages
        run: |
          echo "CCACHE_RPM=$(find $HOME/rpmbuild/RPMS/x86_64/ccache-[0-9]*.rpm)" >> $GITHUB_ENV
      - name: Upload Artifact
        # NB: for centos 6, we cannot create release since the nodejs requires
        # glibc 2.17+
        uses: actions/upload-artifact@v1
        with:
          name: ccache-3.7.7-1.el6.x86_64.rpm
          path: |
            ${{ env.CCACHE_RPM }}

# vim: set ts=2 sw=2:
